/**
 * Sprint 5 Feature B — Markdown export.
 *
 * Pure renderer. No dependencies. Produces the 8-section document
 * described in SPRINT-5-PLAN §6.2.
 */

import type {
  AdvisoryDocument,
  TemplateScore,
  ReviewPlan,
  VariantSet,
} from './types';

function table(headers: string[], rows: string[][]): string {
  const h = `| ${headers.join(' | ')} |`;
  const sep = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map((r) => `| ${r.join(' | ')} |`).join('\n');
  return [h, sep, body].join('\n');
}

export function renderAdvisoryMarkdown(
  doc: AdvisoryDocument,
  score: TemplateScore,
  reviewPlan: ReviewPlan,
  variants?: VariantSet,
): string {
  const lines: string[] = [];
  lines.push(`# ${doc.officeName} — Schedule Advisory`);
  lines.push('');
  lines.push(`**Generated:** ${doc.generatedAt}`);
  lines.push(`**Week:** ${doc.weekLabel}`);
  lines.push(`**Production Policy:** ${doc.productionPolicy}`);
  lines.push(`**Practice Model:** ${doc.practiceModel}`);
  lines.push('');

  lines.push('## 1. Executive Summary');
  lines.push('');
  lines.push(doc.executiveSummary.narrative);
  lines.push('');

  lines.push('## 2. Template Score');
  lines.push('');
  lines.push(
    table(
      ['Axis', 'Score', 'Band'],
      score.axes.map((a) => [a.label, String(a.score), a.band]),
    ),
  );
  lines.push('');
  lines.push(`**Overall:** ${score.overall} / 10 (${score.band})`);
  lines.push('');

  lines.push('## 3. Key Inputs & Assumptions');
  lines.push('');
  lines.push(
    table(
      ['Field', 'Value', 'Source'],
      doc.keyInputs.map((k) => [k.field, k.value, k.source]),
    ),
  );
  lines.push('');

  lines.push('## 4. Recommended Weekly Template');
  lines.push('');
  if (doc.weeklyTemplate.length === 0) {
    lines.push('_No placed blocks yet — run Generate first._');
  } else {
    lines.push(
      table(
        ['Day', 'Time', 'Appointment Type', 'Purpose', 'Notes'],
        doc.weeklyTemplate.map((r) => [r.day, r.timeBlock, r.appointmentType, r.purpose, r.notes]),
      ),
    );
  }
  lines.push('');

  lines.push('## 5. Block Rationale');
  lines.push('');
  for (const r of doc.blockRationale) {
    lines.push(`### ${r.day}`);
    lines.push(r.prose);
    lines.push('');
  }

  lines.push('## 6. Risks & Tradeoffs');
  lines.push('');
  if (doc.risks.length === 0) {
    lines.push('_No risks or tradeoffs recorded — clean Guard Report on all days._');
  } else {
    for (const r of doc.risks) {
      lines.push(`- **[${r.severity.toUpperCase()}${r.ruleCode ? ` ${r.ruleCode}` : ''}]** ${r.plainEnglish}`);
    }
  }
  lines.push('');

  lines.push('## 7. KPIs to Monitor');
  lines.push('');
  let idx = 1;
  for (const k of doc.kpis) {
    lines.push(`${idx}. **${k.metric}** — target: ${k.target}. _${k.whyItMatters}_`);
    idx++;
  }
  lines.push('');

  lines.push('## 8. Review Timeline');
  lines.push('');
  for (const m of reviewPlan.milestones) {
    lines.push(`### Day ${m.day}`);
    lines.push(m.summary);
    lines.push('');
    for (const k of m.kpis) {
      lines.push(`- **${k.metric}** — target: ${k.target}. Watch: ${k.trendToWatch}. Trigger: ${k.revisionTrigger}.`);
    }
    lines.push('');
  }

  lines.push('## 9. "To Raise This Score" Suggestions');
  lines.push('');
  for (const a of score.axes) {
    if (!a.raiseSuggestions.length) continue;
    lines.push(`### ${a.label} (${a.score} → ${Math.min(10, a.score + 1)})`);
    for (const s of a.raiseSuggestions) {
      lines.push(`- ${s}`);
    }
    lines.push('');
  }

  if (variants) {
    lines.push('## 10. Variant Comparison');
    lines.push('');
    lines.push(
      table(
        ['Variant', 'Policy', 'Weekly $', 'NP/wk', 'ER/wk', 'Hygiene', 'Score'],
        variants.variants.map((v) => [
          v.label,
          v.productionPolicy,
          `$${v.headlineKpis.productionTotal.toLocaleString()}`,
          String(v.headlineKpis.npSlotsPerWeek),
          String(v.headlineKpis.erSlotsPerWeek),
          String(v.headlineKpis.hygieneExamsPlaced),
          `${v.score.overall}/10`,
        ]),
      ),
    );
    lines.push('');
    lines.push(`**Recommendation:** ${variants.recommendation.winner} — ${variants.recommendation.reason}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by CST Designer Advisory v1 — Sprint 5._');
  return lines.join('\n');
}

/**
 * "Copy as prompt" — render the filled-in docx-style user prompt from the
 * intake record so a user can sanity-check the template against a raw AI.
 */
export function renderUserPrompt(
  doc: AdvisoryDocument,
  extras: {
    intakeGoalsJson: unknown;
    intakeConstraintsJson: unknown;
  },
): string {
  return [
    `# Custom Schedule Template Request — ${doc.officeName}`,
    '',
    '## PRACTICE',
    `- Name: ${doc.officeName}`,
    `- Model: ${doc.practiceModel}`,
    `- Production policy: ${doc.productionPolicy}`,
    '',
    '## GOALS',
    '```json',
    JSON.stringify(extras.intakeGoalsJson, null, 2),
    '```',
    '',
    '## CONSTRAINTS + ISSUES',
    '```json',
    JSON.stringify(extras.intakeConstraintsJson, null, 2),
    '```',
    '',
    '## OUTPUT REQUEST',
    'Produce a weekly schedule template that respects the goals and constraints above.',
    'Output must include: executive summary, per-day block table, block rationale, risks, KPIs, 30/60/90 review plan.',
    'Score the result 1-10 on six axes: production potential, new-patient access, emergency access, hygiene support, team usability, schedule stability.',
  ].join('\n');
}
