"use client";

import { useEffect, useMemo } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Printer, Download, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useOfficeStore } from "@/store/office-store";
import { useScheduleStore } from "@/store/schedule-store";
import { buildWeeklyReport } from "@/lib/report-helpers";
import type { WeeklyReportData } from "@/lib/report-helpers";

function formatCurrency(n: number): string {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
}

function AchievementBadge({ pct }: { pct: number }) {
  const color = pct >= 100 ? "text-green-700 bg-green-50 border-green-200"
    : pct >= 75 ? "text-blue-700 bg-blue-50 border-blue-200"
    : "text-orange-700 bg-orange-50 border-orange-200";
  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded-full border text-xs font-semibold ${color}`}>
      {pct}%
    </span>
  );
}

export default function WeeklyReportPage() {
  const params = useParams();
  const router = useRouter();
  const officeId = params.id as string;

  const { currentOffice, fetchOffice, isLoading } = useOfficeStore();
  const { generatedSchedules, loadSchedulesForOffice } = useScheduleStore();

  useEffect(() => {
    fetchOffice(officeId).catch(() => router.push("/"));
  }, [officeId, fetchOffice, router]);

  useEffect(() => {
    loadSchedulesForOffice(officeId);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [officeId]);

  const report: WeeklyReportData | null = useMemo(() => {
    if (!currentOffice) return null;
    const providers = currentOffice.providers ?? [];
    const blockTypes = currentOffice.blockTypes ?? [];
    return buildWeeklyReport(
      currentOffice.name,
      generatedSchedules,
      providers,
      blockTypes,
      currentOffice.totalDailyGoal
    );
  }, [currentOffice, generatedSchedules]);

  if (isLoading || !currentOffice || !report) {
    return (
      <div className="flex items-center justify-center h-96">
        <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
      {/* Print CSS */}
      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          @page { size: landscape; margin: 15mm; }
        }
      `}</style>

      <div className="max-w-5xl mx-auto space-y-6 pb-16">
        {/* Toolbar — hidden on print */}
        <div className="no-print flex items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <Link href={`/offices/${officeId}`}>
              <Button variant="ghost" size="icon">
                <ArrowLeft className="w-5 h-5" />
              </Button>
            </Link>
            <div>
              <h1 className="text-lg font-bold">Weekly Schedule Report</h1>
              <p className="text-xs text-muted-foreground">{currentOffice.name}</p>
            </div>
          </div>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => window.print()}
              className="gap-1"
            >
              <Printer className="w-4 h-4" />
              Print
            </Button>
            <Button
              variant="default"
              size="sm"
              onClick={() => window.print()}
              className="gap-1"
            >
              <Download className="w-4 h-4" />
              Download PDF
            </Button>
          </div>
        </div>

        {/* ── Report Content (print-friendly) ── */}
        <div id="report-content" className="bg-white rounded-xl shadow-sm border border-border overflow-hidden print:shadow-none print:border-0">

          {/* ── Header ── */}
          <div className="bg-slate-800 text-white px-8 py-6 print:py-4">
            <div className="flex justify-between items-start">
              <div>
                <h2 className="text-2xl font-bold">{report.officeName}</h2>
                <p className="text-slate-300 text-sm mt-1">Weekly Schedule Report · Week of {report.weekOf}</p>
              </div>
              <div className="text-right">
                <p className="text-slate-400 text-xs">Generated by Schedule Template Designer</p>
                <p className="text-slate-300 text-xs mt-1">{report.generatedAt}</p>
              </div>
            </div>
          </div>

          {/* ── Executive Summary ── */}
          <div className="px-8 py-6 border-b border-border bg-slate-50">
            <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-4">Executive Summary</h3>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
              <div className="text-center">
                <p className="text-2xl font-bold text-foreground">{formatCurrency(report.totalScheduledProduction)}</p>
                <p className="text-xs text-muted-foreground mt-1">Total Scheduled Production</p>
              </div>
              <div className="text-center">
                <p className="text-2xl font-bold text-foreground">{report.goalAchievementPct}%</p>
                <p className="text-xs text-muted-foreground mt-1">Goal Achievement</p>
              </div>
              <div className="text-center">
                <p className="text-2xl font-bold text-foreground">{report.averageQualityScore > 0 ? report.averageQualityScore : "—"}</p>
                <p className="text-xs text-muted-foreground mt-1">Avg Quality Score</p>
              </div>
              <div className="text-center">
                <p className="text-2xl font-bold text-foreground">{report.providerCount}</p>
                <p className="text-xs text-muted-foreground mt-1">Providers · {report.workingDays} Days</p>
              </div>
            </div>
            {/* Goal bar */}
            <div className="mt-4 space-y-1">
              <div className="flex justify-between text-xs text-muted-foreground">
                <span>Production vs Goal</span>
                <span>{formatCurrency(report.totalScheduledProduction)} / {formatCurrency(report.totalGoal)}</span>
              </div>
              <div className="h-2 rounded-full bg-slate-200 overflow-hidden">
                <div
                  className={`h-full rounded-full ${report.goalAchievementPct >= 100 ? "bg-green-500" : report.goalAchievementPct >= 75 ? "bg-blue-500" : "bg-orange-400"}`}
                  style={{ width: `${Math.min(report.goalAchievementPct, 100)}%` }}
                />
              </div>
            </div>
          </div>

          {/* ── Daily Schedule Cards ── */}
          <div className="px-8 py-6 border-b border-border">
            <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-4">Daily Schedule Summary</h3>
            {report.days.length === 0 ? (
              <p className="text-sm text-muted-foreground italic">No schedules generated yet. Go to Template Builder to generate.</p>
            ) : (
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                {report.days.map(day => (
                  <div key={day.dayOfWeek} className="rounded-lg border border-border bg-white p-4 space-y-3">
                    <div className="flex items-center justify-between">
                      <h4 className="text-sm font-semibold text-foreground">{day.label}</h4>
                      <AchievementBadge pct={day.achievementPct} />
                    </div>
                    <div className="space-y-1">
                      <div className="flex justify-between text-xs text-muted-foreground">
                        <span>Scheduled</span>
                        <span className="font-medium text-foreground">{formatCurrency(day.scheduledProduction)}</span>
                      </div>
                      <div className="flex justify-between text-xs text-muted-foreground">
                        <span>Goal</span>
                        <span>{formatCurrency(day.dailyGoal)}</span>
                      </div>
                      <div className="h-1.5 rounded-full bg-slate-100 overflow-hidden mt-2">
                        <div
                          className={`h-full rounded-full ${day.achievementPct >= 100 ? "bg-green-500" : day.achievementPct >= 75 ? "bg-blue-500" : "bg-orange-400"}`}
                          style={{ width: `${Math.min(day.achievementPct, 100)}%` }}
                        />
                      </div>
                    </div>
                    {day.warningCount > 0 && (
                      <p className="text-xs text-yellow-600">
                        ⚠️ {day.warningCount} clinical warning{day.warningCount !== 1 ? "s" : ""}
                      </p>
                    )}
                    {/* Provider schedule block list */}
                    <div className="space-y-1 pt-1 border-t border-border">
                      {day.providers.map(p => (
                        <div key={p.id} className="flex justify-between text-xs">
                          <span className="text-muted-foreground truncate">{p.name}</span>
                          <span className={`font-medium ${p.gap > 0 ? "text-orange-600" : "text-green-600"}`}>
                            {formatCurrency(p.scheduledProduction)}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* ── Procedure Mix Summary ── */}
          {report.procedureMix.length > 0 && (
            <div className="px-8 py-6 border-b border-border">
              <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-4">Procedure Mix Summary</h3>
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-border text-left">
                    <th className="pb-2 text-xs text-muted-foreground font-semibold">Procedure Type</th>
                    <th className="pb-2 text-xs text-muted-foreground font-semibold text-right">Current %</th>
                    <th className="pb-2 text-xs text-muted-foreground font-semibold text-right">Target %</th>
                    <th className="pb-2 text-xs text-muted-foreground font-semibold text-right">Delta</th>
                  </tr>
                </thead>
                <tbody>
                  {report.procedureMix.map((row, i) => (
                    <tr key={i} className="border-b border-border/50 hover:bg-slate-50">
                      <td className="py-1.5 text-foreground">{row.label}</td>
                      <td className="py-1.5 text-right font-medium">{row.currentPct}%</td>
                      <td className="py-1.5 text-right text-muted-foreground">{row.targetPct > 0 ? `${row.targetPct}%` : "—"}</td>
                      <td className={`py-1.5 text-right font-medium ${row.delta > 0 ? "text-green-600" : row.delta < 0 ? "text-red-500" : "text-muted-foreground"}`}>
                        {row.delta !== 0 ? `${row.delta > 0 ? "+" : ""}${row.delta}%` : "—"}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* ── Provider Performance Table ── */}
          <div className="px-8 py-6">
            <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-4">Provider Performance</h3>
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border text-left">
                  <th className="pb-2 text-xs text-muted-foreground font-semibold">Provider</th>
                  <th className="pb-2 text-xs text-muted-foreground font-semibold">Role</th>
                  <th className="pb-2 text-xs text-muted-foreground font-semibold text-right">Daily Goal</th>
                  <th className="pb-2 text-xs text-muted-foreground font-semibold text-right">Scheduled</th>
                  <th className="pb-2 text-xs text-muted-foreground font-semibold text-right">Gap</th>
                </tr>
              </thead>
              <tbody>
                {report.providers.map(p => (
                  <tr key={p.id} className="border-b border-border/50 hover:bg-slate-50">
                    <td className="py-2 font-medium text-foreground">{p.name}</td>
                    <td className="py-2 text-muted-foreground text-xs capitalize">{p.role.toLowerCase()}</td>
                    <td className="py-2 text-right text-muted-foreground">{formatCurrency(p.dailyGoal)}</td>
                    <td className="py-2 text-right font-medium">{formatCurrency(p.scheduledProduction)}</td>
                    <td className={`py-2 text-right font-medium ${p.gap > 0 ? "text-orange-600" : "text-green-600"}`}>
                      {p.gap > 0 ? `-${formatCurrency(p.gap)}` : `+${formatCurrency(Math.abs(p.gap))}`}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* ── Footer ── */}
          <div className="px-8 py-4 bg-slate-50 border-t border-border">
            <p className="text-xs text-muted-foreground text-center">
              Generated by Schedule Template Designer · {report.generatedAt}
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
